default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: postgres_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: postgres_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: postgres_production
  pool: 5
